# Set static IP
# Depends on:
#   vars:
#       interface: "eth0"
#       ipaddress: "192.168.178.100"
#       routers: ["192.168.178.1"]
#       dns_servers: ["8.8.8.8", "8.8.4.4"]
#   handlers:
#       handlers/reboot.yml
#       

- name: Configure static IP in  /etc/dhcpcd.conf
  become: yes
  lineinfile:
    dest:  /etc/dhcpcd.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { regexp: "^interface eth[0-9]$", line: "interface {{ interface }}" }
    - { regexp: "^static ip_address", line: "static ip_address={{ ipaddress }}" }
    - { regexp: "^static routers", line: "static routers={{ routers }}" }
    - { regexp: "^static domain_name_servers", line: "static domain_name_servers={{ dns_servers }}" }
  notify: reboot
