# Run apt-get update and apt-get upgrade 
# Depends on: none
#   

# Update apt packages
- name: Update apt packages
  become: yes
  apt: 
    update_cache=yes
    cache_valid_time=3600

# Upgrade apt packages
- name: Upgrade apt packages
  become: yes
  apt: 
    upgrade=dist
